// e2e/landing.spec.ts
// E2E Scenarios 1 & 2: Landing page load and OAuth initiation.

import { test, expect } from '@playwright/test';

test.describe('Landing Page', () => {
  // Scenario 1: Landing page load
  test('displays the heading and connect button', async ({ page }) => {
    await page.goto('/');

    // Verify h1 contains "Actions Dashboard"
    const heading = page.getByTestId('landing-title');
    await expect(heading).toBeVisible();
    await expect(heading).toContainText('GitHub Actions');

    // Verify the connect button is visible
    const connectButton = page.getByTestId('landing-connect-button');
    await expect(connectButton).toBeVisible();
    await expect(connectButton).toContainText('Connect with GitHub');

    // Verify scope disclosure is visible
    const disclosure = page.getByTestId('landing-scope-disclosure');
    await expect(disclosure).toBeVisible();
  });

  // Scenario 2: OAuth initiation
  test('clicking connect navigates to GitHub OAuth authorize', async ({
    page,
  }) => {
    await page.goto('/');

    // Wait for connect button to be visible
    const connectButton = page.getByTestId('landing-connect-button');
    await expect(connectButton).toBeVisible();

    // Listen for navigation before clicking
    const [request] = await Promise.all([
      page.waitForRequest((req) =>
        req.url().includes('github.com/login/oauth/authorize'),
      ),
      connectButton.click(),
    ]);

    const url = new URL(request.url());

    // Verify the URL is the GitHub OAuth authorize endpoint
    expect(url.hostname).toBe('github.com');
    expect(url.pathname).toBe('/login/oauth/authorize');

    // Verify scope=repo is present
    expect(url.searchParams.get('scope')).toBe('repo');

    // Verify client_id is present (any non-empty value since env may vary)
    const clientId = url.searchParams.get('client_id');
    expect(clientId).toBeTruthy();

    // CSRF protection: state must be a v4 UUID generated by crypto.randomUUID()
    const state = url.searchParams.get('state');
    expect(state).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
    );
  });
});
